import type { Metadata } from "next";
import "./globals.css";

import { Plus_Jakarta_Sans } from 'next/font/google'
import Footer from "@/components/Footer";
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plus-jakarta', // enables use with Tailwind
  display: 'swap',
})

export const metadata: Metadata = {
  title: "CEREBRIQ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={plusJakartaSans.variable}>
      <body
        className={`antialiased`}
      >
       <div className="h-screen">
        {/* navbar */}
        {children}
        <Footer />
        {/* footer   */}
        </div>
      </body>
    </html>
  );
}
